"""Add an Image url to the items type

Revision ID: 7b3cb091d9a8
Revises: 7941967ced93
Create Date: 2025-12-31 19:55:23.777178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3cb091d9a8'
down_revision: Union[str, Sequence[str], None] = '7941967ced93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemtype', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemtype', 'image_url')
    # ### end Alembic commands ###
