"""add internal_description field

Revision ID: 9081ea90b1f4
Revises: 
Create Date: 2025-12-23 20:03:07.494548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9081ea90b1f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'branch_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('fk_address_missing_item'), 'address', type_='foreignkey')
    op.drop_column('address', 'missing_item_id')
    op.add_column('item', sa.Column('internal_description', sa.Text(), nullable=True))
    op.alter_column('item', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('item', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_item_approved_claim_id'), table_name='item')
    op.drop_index(op.f('ix_item_is_hidden'), table_name='item')
    op.drop_index(op.f('ix_item_status'), table_name='item')
    op.alter_column('user', 'user_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user', 'user_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'external'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_item_status'), 'item', ['status'], unique=False)
    op.create_index(op.f('ix_item_is_hidden'), 'item', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_item_approved_claim_id'), 'item', ['approved_claim_id'], unique=False)
    op.alter_column('item', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('item', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('item', 'internal_description')
    op.add_column('address', sa.Column('missing_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_address_missing_item'), 'address', 'missingitem', ['missing_item_id'], ['id'])
    op.alter_column('address', 'branch_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
