"""add timestamps to permissions

Revision ID: c6a62b01ef98
Revises: 9fca21119157
Create Date: 2025-07-07 21:25:38.240566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a62b01ef98'
down_revision: Union[str, Sequence[str], None] = '9fca21119157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###
